use std::{collections::HashMap, path::Path};

use kairo_core::{ComponentHash, Durability, Workflow};

use super::PreparedStep;
use crate::{
    Result, Runtime, RuntimeError,
    durability_plan::{self, AutoResolution},
    identity,
};

impl Runtime {
    /// profile key for `.kairo/profiles/<shape>.json`.
    pub fn workflow_shape(&self, workflow: &Workflow) -> Result<String> {
        let prepared = self.prepare_workflow(workflow)?;
        Ok(shape_of(workflow.name(), &named_hashes(&prepared)))
    }

    /// same as `workflow_shape`, for a `mode: value` workflow's own (differently-typed) prepared
    /// steps.
    pub fn value_workflow_shape(&self, workflow: &Workflow) -> Result<String> {
        let prepared = self.prepare_value_workflow(workflow)?;
        Ok(shape_of(
            workflow.name(),
            &prepared
                .iter()
                .map(|step| (step.name().to_owned(), step.hash()))
                .collect::<Vec<_>>(),
        ))
    }

    /// the real, previously-measured checkpoint size for this edge, if a Phase 13 profile
    /// exists -- `None` (never `0`) when nothing has been measured yet.
    pub fn edge_checkpoint_bytes(&self, workflow: &Workflow, index: usize) -> Result<Option<u64>> {
        let prepared = self.prepare_workflow(workflow)?;
        let shape = self.workflow_shape(workflow)?;
        let Some(step) = prepared.get(index) else {
            return Ok(None);
        };
        Ok(durability_plan::load_profile(&shape)
            .and_then(|workflow_profile| workflow_profile.edges.get(&step.name).cloned())
            .map(|profile| profile.checkpoint_bytes))
    }

    /// resolves a run's full durability plan once, independent of any particular
    /// ExecutionGroup's own journal -- callers persist the result and thread it into every
    /// group's `Cell::open` as `auto_plan`, never calling this a second time for the same run.
    pub fn resolve_run_plan(
        &self,
        workflow: &Workflow,
        state_path: &Path,
    ) -> Result<(HashMap<usize, bool>, Vec<AutoResolution>)> {
        let prepared = self.prepare_workflow(workflow)?;
        self.resolve_durability(workflow, &prepared, state_path)
    }

    /// resolves `durability: auto` edges for a `mode: value` workflow through the exact same
    /// Phase 14 profile/planner path scalar workflows already use -- a workflow generated by
    /// `kairo workflow new`/`create` always defaults to `auto`, so value-mode runs must be able
    /// to resolve it too, not just reject it.
    pub fn resolve_value_run_plan(
        &self,
        workflow: &Workflow,
        state_path: &Path,
    ) -> Result<(HashMap<usize, bool>, Vec<AutoResolution>)> {
        let prepared = self.prepare_value_workflow(workflow)?;
        self.resolve_durability_for(workflow, &named_hashes_value(&prepared), state_path)
    }

    pub fn auto_edge_profile(&self, workflow: &Workflow, index: usize) -> Result<Option<String>> {
        let (shape, name) = if workflow.mode() == kairo_core::WorkflowMode::Value {
            let prepared = self.prepare_value_workflow(workflow)?;
            (
                self.value_workflow_shape(workflow)?,
                prepared[index].name().to_owned(),
            )
        } else {
            let prepared = self.prepare_workflow(workflow)?;
            (self.workflow_shape(workflow)?, prepared[index].name.clone())
        };
        let Some(profile) = durability_plan::load_profile(&shape)
            .and_then(|workflow_profile| workflow_profile.edges.get(&name).cloned())
        else {
            return Ok(None);
        };
        let (required, reason) = durability_plan::decide(&profile);
        let label = if required { "required" } else { "ephemeral" };
        Ok(Some(format!("{label} · {reason}")))
    }

    /// the real sample count behind this edge's profile, if one exists -- `None` when no profile
    /// exists yet, never `0` for "unknown". Lets a caller decide whether an existing profile is
    /// still too thin to trust (see `durability_plan::MIN_TRUSTED_SAMPLES`) without duplicating
    /// `auto_edge_profile`'s own label-formatting.
    pub fn auto_edge_profile_samples(
        &self,
        workflow: &Workflow,
        index: usize,
    ) -> Result<Option<u32>> {
        let (shape, name) = if workflow.mode() == kairo_core::WorkflowMode::Value {
            let prepared = self.prepare_value_workflow(workflow)?;
            (
                self.value_workflow_shape(workflow)?,
                prepared[index].name().to_owned(),
            )
        } else {
            let prepared = self.prepare_workflow(workflow)?;
            (self.workflow_shape(workflow)?, prepared[index].name.clone())
        };
        Ok(durability_plan::load_profile(&shape)
            .and_then(|workflow_profile| workflow_profile.edges.get(&name).cloned())
            .map(|profile| profile.samples))
    }

    /// folds this cell's own real measurements for every `durability: auto` edge back into its
    /// persisted profile -- the mechanism that makes "use profiles automatically" literally true:
    /// every ordinary run keeps the profile fresh, not just an explicit `kairo workflow profile`.
    /// Never fails the caller's run; a write-back problem is the caller's to log and ignore.
    pub fn record_profile_observations(
        &self,
        workflow: &Workflow,
        state_path: &Path,
    ) -> Result<()> {
        let inspection = crate::inspect_cell(state_path)
            .map_err(|source| self.journal_error(state_path, source))?;
        let shape = self.workflow_shape(workflow)?;
        durability_plan::record_observations(workflow, &shape, &inspection.components, |c| {
            (
                c.index,
                c.duration_us,
                c.durable_after,
                c.checkpoint_bytes,
                c.checkpoint_duration_us,
            )
        })
        .map_err(|source| RuntimeError::ProfileWrite { source })
    }

    // resumed runs reuse the journaled decision (`peek_plan`); fresh runs resolve from a real,
    // previously measured profile and return the resolutions for `Cell::open` to journal.
    pub(super) fn resolve_durability(
        &self,
        workflow: &Workflow,
        prepared: &[PreparedStep],
        state_path: &Path,
    ) -> Result<(HashMap<usize, bool>, Vec<AutoResolution>)> {
        self.resolve_durability_for(workflow, &named_hashes(prepared), state_path)
    }

    fn resolve_durability_for(
        &self,
        workflow: &Workflow,
        steps: &[(String, ComponentHash)],
        state_path: &Path,
    ) -> Result<(HashMap<usize, bool>, Vec<AutoResolution>)> {
        let auto_indices: Vec<usize> = (0..steps.len())
            .filter(|&index| workflow.durability_after_step(index) == Durability::Auto)
            .collect();
        if auto_indices.is_empty() {
            return Ok((HashMap::new(), Vec::new()));
        }
        let peeked = durability_plan::peek_plan(state_path)
            .map_err(|source| self.journal_error(state_path, source))?;
        let shape = shape_of(workflow.name(), steps);
        let mut resolved = HashMap::new();
        let mut auto_plan = Vec::new();
        for index in auto_indices {
            if let Some(required) = peeked.as_ref().and_then(|plan| plan.get(&index)).copied() {
                resolved.insert(index, required);
                continue;
            }
            let (name, _) = &steps[index];
            let profile = durability_plan::load_profile(&shape)
                .and_then(|workflow_profile| workflow_profile.edges.get(name).cloned())
                .ok_or_else(|| RuntimeError::DurabilityProfileMissing { step: name.clone() })?;
            let (required, reason) = durability_plan::decide(&profile);
            resolved.insert(index, required);
            auto_plan.push(AutoResolution {
                index,
                required,
                profile_id: shape.clone(),
                reason,
                profile: Some(profile),
            });
        }
        Ok((resolved, auto_plan))
    }
}

fn shape_of(workflow_name: &str, steps: &[(String, ComponentHash)]) -> String {
    identity::workflow_shape(workflow_name, steps)
}

fn named_hashes(prepared: &[PreparedStep]) -> Vec<(String, ComponentHash)> {
    prepared
        .iter()
        .map(|step| (step.name.clone(), step.hash))
        .collect()
}

fn named_hashes_value(
    prepared: &[super::value::PreparedValueStep],
) -> Vec<(String, ComponentHash)> {
    prepared
        .iter()
        .map(|step| (step.name().to_owned(), step.hash()))
        .collect()
}
