workflow: celsius-to-fahrenheit-durable
input: 20

steps:
  - name: multiply-by-nine
    component: ../basic/multiply-by-nine.wat
  - name: divide-by-five
    component: ../basic/divide-by-five.wat
  - name: add-thirty-two
    component: ../basic/add-thirty-two.wat

edges:
  - from: multiply-by-nine
    to: divide-by-five
  - from: divide-by-five
    to: add-thirty-two
    durability: required
